
package com.ActividadGrand;

import com.Resultados.dlgResultadoG;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class frmActividadTresGrand extends javax.swing.JFrame {

    public frmActividadTresGrand() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Primera orden
        ImageIcon a1 = new ImageIcon("src/com/Recursos/Face/1 cabeza head.png");
        Icon icono1 = new ImageIcon(a1.getImage().getScaledInstance(jlblHead.getWidth(), jlblHead.getHeight(), Image.SCALE_SMOOTH));
        jlblHead.setIcon(icono1);
        
        ImageIcon a3 = new ImageIcon("src/com/Recursos/Face/3 ojos eyes.png");
        Icon icono3 = new ImageIcon(a3.getImage().getScaledInstance(jlblEye.getWidth(), jlblEye.getHeight(), Image.SCALE_SMOOTH));
        jlblEye.setIcon(icono3);
        
        ImageIcon a6 = new ImageIcon("src/com/Recursos/Face/6 boca mouth.png");
        Icon icono6 = new ImageIcon(a6.getImage().getScaledInstance(jlblMouth.getWidth(), jlblMouth.getHeight(), Image.SCALE_SMOOTH));
        jlblMouth.setIcon(icono6);
        
        ImageIcon a5 = new ImageIcon("src/com/Recursos/Face/5 nariz nose.png");
        Icon icono5 = new ImageIcon(a5.getImage().getScaledInstance(jlblNose.getWidth(), jlblNose.getHeight(), Image.SCALE_SMOOTH));
        jlblNose.setIcon(icono5);
        
        //Segunda orden
        ImageIcon s1 = new ImageIcon("src/com/Recursos/Superior/1 shoulder hombro.png");
        Icon iconos1 = new ImageIcon(s1.getImage().getScaledInstance(jlblShoulder.getWidth(), jlblShoulder.getHeight(), Image.SCALE_SMOOTH));
        jlblShoulder.setIcon(iconos1);
        
        ImageIcon i1 = new ImageIcon("src/com/Recursos/Inferior/1 hip cadera.png");
        Icon iconoi1 = new ImageIcon(i1.getImage().getScaledInstance(jlblHip.getWidth(), jlblHip.getHeight(), Image.SCALE_SMOOTH));
        jlblHip.setIcon(iconoi1);
        
        ImageIcon i2 = new ImageIcon("src/com/Recursos/Inferior/2 leg pierna.png");
        Icon iconoi2 = new ImageIcon(i2.getImage().getScaledInstance(jlblLeg.getWidth(), jlblLeg.getHeight(), Image.SCALE_SMOOTH));
        jlblLeg.setIcon(iconoi2);
        
        ImageIcon i3 = new ImageIcon("src/com/Recursos/Inferior/3 knee rodilla.png");
        Icon iconoi3 = new ImageIcon(i3.getImage().getScaledInstance(jlblKnee.getWidth(), jlblKnee.getHeight(), Image.SCALE_SMOOTH));
        jlblKnee.setIcon(iconoi3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jlblOrden1 = new javax.swing.JLabel();
        jlblHead = new javax.swing.JLabel();
        jlblEye = new javax.swing.JLabel();
        jrbHand1 = new javax.swing.JRadioButton();
        jrbLegs1 = new javax.swing.JRadioButton();
        jrbHead1 = new javax.swing.JRadioButton();
        jrbEye2 = new javax.swing.JRadioButton();
        jrbNose2 = new javax.swing.JRadioButton();
        jrbEars2 = new javax.swing.JRadioButton();
        jlblMouth = new javax.swing.JLabel();
        jrbNose3 = new javax.swing.JRadioButton();
        jrbMouth3 = new javax.swing.JRadioButton();
        jrbEars3 = new javax.swing.JRadioButton();
        jlblNose = new javax.swing.JLabel();
        jrbNose4 = new javax.swing.JRadioButton();
        jrbHead4 = new javax.swing.JRadioButton();
        jrbHair4 = new javax.swing.JRadioButton();
        jlblOrden2 = new javax.swing.JLabel();
        jlblShoulder = new javax.swing.JLabel();
        jlblAudio_shoulder = new javax.swing.JLabel();
        jtxfShoulder = new javax.swing.JTextField();
        jlblHip = new javax.swing.JLabel();
        jlblAudio_hip = new javax.swing.JLabel();
        jtxfHip = new javax.swing.JTextField();
        jlblLeg = new javax.swing.JLabel();
        jlblAudio_leg = new javax.swing.JLabel();
        jtxfLeg = new javax.swing.JTextField();
        jlblKnee = new javax.swing.JLabel();
        jlblAudio_knee = new javax.swing.JLabel();
        jtxfKnee = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 1810));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1810));

        jlblTitulo.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jlblTitulo.setText("Activity 3: Parts of the human body.");

        jlblOrden1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jlblOrden1.setText("1) Select the parts of the body.");

        jlblHead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblEye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(jrbHand1);
        jrbHand1.setText("Hand");

        buttonGroup1.add(jrbLegs1);
        jrbLegs1.setText("Legs");

        buttonGroup1.add(jrbHead1);
        jrbHead1.setText("Head");

        buttonGroup2.add(jrbEye2);
        jrbEye2.setText("Eye");

        buttonGroup2.add(jrbNose2);
        jrbNose2.setText("Nose");

        buttonGroup2.add(jrbEars2);
        jrbEars2.setText("Ears");

        jlblMouth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup3.add(jrbNose3);
        jrbNose3.setText("Nose");

        buttonGroup3.add(jrbMouth3);
        jrbMouth3.setText("Mouth");

        buttonGroup3.add(jrbEars3);
        jrbEars3.setText("Ears");

        jlblNose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup4.add(jrbNose4);
        jrbNose4.setText("Nose");

        buttonGroup4.add(jrbHead4);
        jrbHead4.setText("Head");

        buttonGroup4.add(jrbHair4);
        jrbHair4.setText("Hair");

        jlblOrden2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jlblOrden2.setText("2) Listen and write the correct name");

        jlblShoulder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblAudio_shoulder.setText("Audio");

        jlblHip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblAudio_hip.setText("Audio");

        jlblLeg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblAudio_leg.setText("Audio");

        jlblKnee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblAudio_knee.setText("Audio");

        btnOk.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTitulo)
                            .addComponent(jlblOrden1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblEye, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMouth, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbHand1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbLegs1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbHead1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbEye2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbNose2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbEars2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbNose3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbMouth3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbEars3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbNose4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbHead4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbHair4))))
                            .addComponent(jlblNose, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblOrden2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblShoulder, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblHip, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblAudio_shoulder)
                                    .addComponent(jlblAudio_hip)
                                    .addComponent(jlblAudio_leg)
                                    .addComponent(jlblAudio_knee))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxfShoulder, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jtxfHip)
                                    .addComponent(jtxfLeg)
                                    .addComponent(jtxfKnee)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblKnee, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblOrden1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbHand1)
                                .addComponent(jrbLegs1)
                                .addComponent(jrbHead1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblEye, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbEye2)
                                .addComponent(jrbNose2)
                                .addComponent(jrbEars2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblMouth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbNose3)
                                .addComponent(jrbMouth3)
                                .addComponent(jrbEars3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblNose, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbNose4)
                                .addComponent(jrbHead4)
                                .addComponent(jrbHair4)))
                        .addGap(18, 18, 18)
                        .addComponent(jlblOrden2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblShoulder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblAudio_shoulder)
                                .addComponent(jtxfShoulder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblHip, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblAudio_hip)
                                .addComponent(jtxfHip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblAudio_leg)
                                .addComponent(jtxfLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblKnee, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblAudio_knee)
                                .addComponent(jtxfKnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        dlgResultadoG resul = new dlgResultadoG(this, rootPaneCheckingEnabled);
        resul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActividadTresGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActividadTresGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActividadTresGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActividadTresGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmActividadTresGrand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblAudio_hip;
    private javax.swing.JLabel jlblAudio_knee;
    private javax.swing.JLabel jlblAudio_leg;
    private javax.swing.JLabel jlblAudio_shoulder;
    private javax.swing.JLabel jlblEye;
    private javax.swing.JLabel jlblHead;
    private javax.swing.JLabel jlblHip;
    private javax.swing.JLabel jlblKnee;
    private javax.swing.JLabel jlblLeg;
    private javax.swing.JLabel jlblMouth;
    private javax.swing.JLabel jlblNose;
    private javax.swing.JLabel jlblOrden1;
    private javax.swing.JLabel jlblOrden2;
    private javax.swing.JLabel jlblShoulder;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JRadioButton jrbEars2;
    private javax.swing.JRadioButton jrbEars3;
    private javax.swing.JRadioButton jrbEye2;
    private javax.swing.JRadioButton jrbHair4;
    private javax.swing.JRadioButton jrbHand1;
    private javax.swing.JRadioButton jrbHead1;
    private javax.swing.JRadioButton jrbHead4;
    private javax.swing.JRadioButton jrbLegs1;
    private javax.swing.JRadioButton jrbMouth3;
    private javax.swing.JRadioButton jrbNose2;
    private javax.swing.JRadioButton jrbNose3;
    private javax.swing.JRadioButton jrbNose4;
    private javax.swing.JTextField jtxfHip;
    private javax.swing.JTextField jtxfKnee;
    private javax.swing.JTextField jtxfLeg;
    private javax.swing.JTextField jtxfShoulder;
    // End of variables declaration//GEN-END:variables
}
