/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Actividades;


import DAO.Modelo.Ninos;
import com.ActividadGrand.frmTopicoUnoGrand;
import com.Edades.frmEdades;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class frmActividadGrand extends javax.swing.JFrame {

    /**
     * Creates new form frmActividadGrand
     */
    public frmActividadGrand() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public frmActividadGrand(Ninos usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JButton getBtnEdad() {
        return BtnEdad;
    }

    public JButton getBtnG1() {
        return btnG1;
    }

    public JButton getBtnG2() {
        return btnG2;
    }

    public JButton getBtnG3() {
        return btnG3;
    }

    public JButton getBtnG4() {
        return btnG4;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnG1 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        BtnEdad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividades Mariposa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnG1.setBackground(new java.awt.Color(0, 153, 102));
        btnG1.setFont(new java.awt.Font("Segoe Print", 0, 40)); // NOI18N
        btnG1.setText("Date ");
        btnG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnG1MouseClicked(evt);
            }
        });

        btnG2.setBackground(new java.awt.Color(255, 0, 153));
        btnG2.setFont(new java.awt.Font("Segoe Print", 0, 40)); // NOI18N
        btnG2.setText("Present Continuos");
        btnG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnG2MouseClicked(evt);
            }
        });

        btnG3.setBackground(new java.awt.Color(0, 153, 204));
        btnG3.setFont(new java.awt.Font("Segoe Print", 0, 40)); // NOI18N
        btnG3.setText("Past Simple");
        btnG3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnG3MouseClicked(evt);
            }
        });

        btnG4.setBackground(new java.awt.Color(255, 0, 0));
        btnG4.setFont(new java.awt.Font("Segoe Print", 0, 40)); // NOI18N
        btnG4.setText("Irregulars Verbs");
        btnG4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnG4MouseClicked(evt);
            }
        });

        BtnEdad.setText("<--   Escoger Otra Dificultad");
        BtnEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEdadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnG4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnG1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnG1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnG2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnG3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnG4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BtnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEdadMouseClicked
        
    }//GEN-LAST:event_BtnEdadMouseClicked

    private void btnG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnG1MouseClicked
        
    }//GEN-LAST:event_btnG1MouseClicked

    private void btnG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnG2MouseClicked
//        frmTopicoDosGrand tg2 = new frmTopicoDosGrand();
//        tg2.setVisible(true);
        
    }//GEN-LAST:event_btnG2MouseClicked

    private void btnG3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnG3MouseClicked
//        frmTopicoTresGrand tg3 = new frmTopicoTresGrand();
//        tg3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnG3MouseClicked

    private void btnG4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnG4MouseClicked
//        frmTopicoCuatroGrand tg4 = new frmTopicoCuatroGrand();
//        tg4.setVisible(true);
        
    }//GEN-LAST:event_btnG4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActividadGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActividadGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActividadGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActividadGrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmActividadGrand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEdad;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JButton btnG4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
