/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author PROGRAMADOR.GYE
 */
public class PlantillaActividad extends javax.swing.JFrame {

    /**
     * Creates new form PlantillaActividad
     */
    public PlantillaActividad() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JRadioButton getRdb1() {
        return Rdb1;
    }

    public JRadioButton getRdb2() {
        return Rdb2;
    }

    public JRadioButton getRdb3() {
        return Rdb3;
    }

    public JRadioButton getRdb4() {
        return Rdb4;
    }

    public JRadioButton getRdb5() {
        return Rdb5;
    }

    public JRadioButton getRdb6() {
        return Rdb6;
    }

    public JButton getBtnTerminar() {
        return btnTerminar;
    }

    public JLabel getLblPreguntaCompl3() {
        return lblPreguntaCompl3;
    }

    public JLabel getLblPreguntaCompl4() {
        return lblPreguntaCompl4;
    }

    public JLabel getLblPreguntaSelect1() {
        return lblPreguntaSelect1;
    }

    public JLabel getLblPreguntaSelect2() {
        return lblPreguntaSelect2;
    }

    public JPanel getPanel3() {
        return panelS;
    }

    public JTextField getTxtRespuesta1() {
        return txtRespuesta1;
    }

    public JTextField getTxtRespuesta2() {
        return txtRespuesta2;
    }

    public JPanel getPanelC() {
        return panelC;
    }

    public JPanel getPanelS() {
        return panelS;
    }

    public JLabel getLblConfir1() {
        return lblConfir1;
    }

    public JLabel getLblConfir2() {
        return lblConfir2;
    }

    public JLabel getLblConfir3() {
        return lblConfir3;
    }

    public JLabel getLblConfir4() {
        return lblConfir4;
    }

    public JLabel getLblRespC1() {
        return lblRespC1;
    }

    public JLabel getLblRespC2() {
        return lblRespC2;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelS = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Rdb1 = new javax.swing.JRadioButton();
        Rdb2 = new javax.swing.JRadioButton();
        Rdb3 = new javax.swing.JRadioButton();
        lblPreguntaSelect1 = new javax.swing.JLabel();
        lblPreguntaSelect2 = new javax.swing.JLabel();
        Rdb4 = new javax.swing.JRadioButton();
        Rdb5 = new javax.swing.JRadioButton();
        Rdb6 = new javax.swing.JRadioButton();
        lblConfir2 = new javax.swing.JLabel();
        lblConfir1 = new javax.swing.JLabel();
        panelC = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblPreguntaCompl3 = new javax.swing.JLabel();
        txtRespuesta1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblPreguntaCompl4 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblConfir3 = new javax.swing.JLabel();
        lblConfir4 = new javax.swing.JLabel();
        lblRespC1 = new javax.swing.JLabel();
        lblRespC2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelS.setBackground(new java.awt.Color(255, 255, 255));
        panelS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setText("Seleccione la respuesta correcta:");
        panelS.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 30));

        Rdb1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rdb1);
        Rdb1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Rdb1.setText("jRadioButton1");
        panelS.add(Rdb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Rdb2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rdb2);
        Rdb2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Rdb2.setText("jRadioButton1");
        panelS.add(Rdb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        Rdb3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rdb3);
        Rdb3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Rdb3.setText("jRadioButton1");
        panelS.add(Rdb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        lblPreguntaSelect1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblPreguntaSelect1.setText("PREGUNTA");
        panelS.add(lblPreguntaSelect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 510, 30));

        lblPreguntaSelect2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblPreguntaSelect2.setText("PREGUNTA");
        panelS.add(lblPreguntaSelect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 510, 30));

        Rdb4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rdb4);
        Rdb4.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Rdb4.setText("jRadioButton1");
        panelS.add(Rdb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Rdb5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rdb5);
        Rdb5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Rdb5.setText("jRadioButton1");
        panelS.add(Rdb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        Rdb6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rdb6);
        Rdb6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Rdb6.setText("jRadioButton1");
        panelS.add(Rdb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        lblConfir2.setText("jLabel2");
        panelS.add(lblConfir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        lblConfir1.setText("jLabel2");
        panelS.add(lblConfir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jPanel1.add(panelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 550, 250));

        panelC.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel5.setText("Complete la oracion:");

        lblPreguntaCompl3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblPreguntaCompl3.setText("He ________yesterday in my house");

        txtRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel9.setText("Respuesta:");

        lblPreguntaCompl4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblPreguntaCompl4.setText("He ________yesterday in my house");

        txtRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel10.setText("Respuesta:");

        lblConfir3.setText("jLabel2");

        lblConfir4.setText("jLabel2");

        lblRespC1.setText("jLabel2");

        lblRespC2.setText("jLabel2");

        javax.swing.GroupLayout panelCLayout = new javax.swing.GroupLayout(panelC);
        panelC.setLayout(panelCLayout);
        panelCLayout.setHorizontalGroup(
            panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(txtRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(lblConfir3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(panelCLayout.createSequentialGroup()
                        .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreguntaCompl3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCLayout.createSequentialGroup()
                        .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(txtRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(lblConfir4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRespC1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRespC2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreguntaCompl4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelCLayout.setVerticalGroup(
            panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblPreguntaCompl3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfir3)
                    .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblRespC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPreguntaCompl4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfir4)
                    .addComponent(txtRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRespC2)
                .addGap(23, 23, 23))
        );

        jPanel1.add(panelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 306, 550, 290));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTIVITY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 40));

        btnTerminar.setBackground(new java.awt.Color(0, 0, 204));
        btnTerminar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnTerminar.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminar.setText("TERMINAR ACTIVIDAD");
        jPanel1.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 601, 570, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta1ActionPerformed

    private void txtRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantillaActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantillaActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantillaActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantillaActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantillaActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rdb1;
    private javax.swing.JRadioButton Rdb2;
    private javax.swing.JRadioButton Rdb3;
    private javax.swing.JRadioButton Rdb4;
    private javax.swing.JRadioButton Rdb5;
    private javax.swing.JRadioButton Rdb6;
    private javax.swing.JButton btnTerminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfir1;
    private javax.swing.JLabel lblConfir2;
    private javax.swing.JLabel lblConfir3;
    private javax.swing.JLabel lblConfir4;
    private javax.swing.JLabel lblPreguntaCompl3;
    private javax.swing.JLabel lblPreguntaCompl4;
    private javax.swing.JLabel lblPreguntaSelect1;
    private javax.swing.JLabel lblPreguntaSelect2;
    private javax.swing.JLabel lblRespC1;
    private javax.swing.JLabel lblRespC2;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelS;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    // End of variables declaration//GEN-END:variables
}
